/*
 * This source file was generated by the Gradle 'init' task
 */
package io.pbhuyan.gradle.spring;

import io.pbhuyan.gradle.spring.tasks.GenerateBannerTask;
import io.pbhuyan.gradle.spring.tasks.PrintAllBannersTask;
import io.pbhuyan.gradle.spring.tasks.PrintBannerTask;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;


public class SpringBannerGeneratorPlugin implements Plugin<Project> {
    public void apply(@NotNull Project project) {
        SpringBannerExtension.create(project);
        GenerateBannerTask.register(project);
        PrintBannerTask.register(project);
        PrintAllBannersTask.register(project);
    }
}
