plugins {
    java
    id("org.springframework.boot").version("3.5.5")
    id("io.spring.dependency-management").version("1.1.7")
    id("io.github.bhuyanp.spring-banner-gradle-plugin")
}

group = "io.pbhuyan.gradle"
version = "1.0.1"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.withType<Test> {
    useJUnitPlatform()
}

//springBanner {
//    generateBanner = true // Flag to generate top section of the banner. Default is true.
//    generateCaption = true // Flag to generate bottom section(caption) of the banner. Default is true.
//    bannerText = "Funky Banner" // Custom banner text. Default is project name(capitalized).
//    themePreset =
//        THEME_PRESET.SURPRISE_ME // Theme preset to use for the banner styling. Default is SURPRISE_ME. Other options include DARK, LIGHT, SURPRISE_ME_LIGHT etc.
//    bannerFonts = listOf(
//        "3d",
//        "4max"
//    ) // One or more fonts to use for the banner text. By default, plugin uses a default set of fonts that are tested to work well with the banner text. You can specify multiple fonts and the plugin will randomly pick one for each build.
//    captionSetting =
//        CaptionSetting.builder() // Caption settings for the fine grain control over banner caption. It includes options like caption bullet style, whether to hide several versions etc.
//            .text(
//                """
//            App: ${'$'}appVersion
//            Spring Boot: ${'$'}springBootVersion
//            JDK: ${'$'}jdkVersion
//            Gradle: ${'$'}gradleVersion
//            XYZ Library: 1.0.0
//        """.trimIndent())
//            /* Custom caption text to override default caption generated by the plugin. Default caption includes Spring Boot version, JDK version and Gradle version. You can use the following variables in the caption text to include dynamic values:
//                    ${'$'}appVersion - The version of your application (from build file)
//                    ${'$'}springBootVersion - The version of Spring Boot being used
//                    ${'$'}jdkVersion - The version of JDK being used
//                    ${'$'}gradleVersion - The version of Gradle being used
//             */
//            .hideAppVersion(false) // Whether to hide the app version in the caption. Default is false.
//            .hideSpringBootVersion(false) // Whether to hide the Spring Boot version in the caption. Default is false.
//            .hideJDKVersion(false) // Whether to hide the JDK. Default is false.
//            .hideGradleVersion(false) // Whether to hide the Gradle version in the caption. Default is false.
//            .captionBulletStyle(CaptionSetting.CAPTION_BULLET_STYLE.GT) // Bullet style to use for the caption. Default is GT (greater than symbol). Other options include PIPE("|"),GTA("->"),POUND("#"),DASH("-"),DOLLAR("$"),RANDOM("Random"),NONE("").
//            .build() // Caption settings for the fine grain control over banner caption. It includes options like caption bullet style, whether to hide several versions etc.
//}