/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.bhuyanp.gradle;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class SpringBannerGeneratorPluginTest {

}
