/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.bhuyanp.gradle;

import io.github.bhuyanp.gradle.tasks.GenerateBannerTask;
import io.github.bhuyanp.gradle.tasks.PrintAllBannersTask;
import io.github.bhuyanp.gradle.tasks.PrintBannerTask;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.jetbrains.annotations.NotNull;

/**
 * Springboot banner generator plugin creates colorful banner for spring application.
 *
 * Tasks include:
 * <ul>
 *     <li>{@link GenerateBannerTask} [DEFAULT]</li>
 *     <li>{@link PrintBannerTask} - Prints banner in the console as per current app's configuration</li>
 *     <li>{@link PrintAllBannersTask} - Prints banners in the console using all the fonts available in the library</li>
 * </ul>
 *
 * @author Prasanta Bhuyan
 * @since 1.0
 */
public class SpringBannerGeneratorPlugin implements Plugin<Project> {
    /**
     *
     * @param project The target object
     * @since 1.0
     */
    public void apply(@NotNull Project project) {
        SpringBannerExtension.create(project);
        GenerateBannerTask.register(project);
        PrintBannerTask.register(project);
        PrintAllBannersTask.register(project);
    }
}
