package io.github.bhuyanp.gradle.model;

import lombok.Builder;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Builder
@Getter
public class CaptionSetting {
    /**
     * Custom caption text to override default caption generated by the plugin.
     * <br/>
     * <br/>
     * Following dynamic placeholder are available:<br/>
     * $appVersion - Application version from build file<br/>
     * $springBootVersion - Spring Boot version<br/>
     * $jdkVersion - JDK version used to run the build<br/>
     * $gradleVersion - Gradle version used to run the build<br/>
     * $activeProfiles - Spring active profiles<br/>
     * <br/>
     * Default: blank<br/>
     * Example: <br/>"App: $appVersion | Spring Boot: $springBootVersion | JDK: $jdkVersion | Gradle: $gradleVersion"
     */
    private String text;

    /**
     * Option to hide application version from the caption automatically generated by the plugin.
     * <br/>
     * Default: false
     */
    private boolean hideAppVersion;
    /**
     * Option to hide springboot version from the caption automatically generated by the plugin.
     * <br/>
     * Default: false
     */
    private boolean hideSpringBootVersion;
    /**
     * Option to hide jdk version from the caption automatically generated by the plugin.
     * <br/>
     * Default: false
     */
    private boolean hideJDKVersion;
    /**
     * Option to hide gradle version from the caption automatically generated by the plugin.
     * <br/>
     * Default: false
     */
    private boolean hideGradleVersion;

    /**
     * Option to set bullet style for the caption. It will be applied to all the lines in the caption.
     * <br/>
     * Default: CaptionSetting.CAPTION_BULLET_STYLE.GT  (">")
     * <br/>
     * Available styles:<br/>
     * GT(">")<br/>
     * PIPE("|")<br/>
     * GTA("->")<br/>
     * POUND("#")<br/>
     * DASH("-")<br/>
     * DOLLAR("$")<br/>
     * RANDOM("Random")<br/>
     * NONE("")
     */
    private CAPTION_BULLET_STYLE captionBulletStyle;

    @RequiredArgsConstructor
    @Getter
    public enum CAPTION_BULLET_STYLE {
        GT(">"),
        PIPE("|"),
        GTA("->"),
        POUND("#"),
        DASH("-"),
        DOLLAR("$"),
        RANDOM("Random"),
        NONE("");

        private final String label;


        @Override
        public String toString() {
            return label;
        }
    }
}
